[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
ethereum = "${ETHEREUM_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
base = { url = "https://api.basescan.org/api", key = "${ETHERSCAN_API_KEY}" }
